hFig = figure('Name','APP',...
    'Numbertitle','off',...
    'Position', [0 -170 1936 1964   ],...
    'WindowStyle','modal',...
    'Color',[0.5 0.5 0.5],...
    'Toolbar','none');
img = imread('welcome.jpg');
img = imresize(img,[864 1536]);
fpos = get(hFig,'Position');
axOffset = (fpos(3:4)-[size(img,2) size(img,1)])/2;
ha = axes('Parent',hFig,'Units','pixels',...
            'Position',[axOffset size(img,2) size(img,1)]);
hImshow = imshow(img,'Parent',ha);
pause(4);
close all force;