f = figure;
p = uipanel(f,'Title','The Image Editor',...
             'Position',[.25 .1 .5 .8]);
 b1 = uicontrol(p,'Style','pushbutton','String','Take photo','Callback',@buttonFunction,...
                'Units','normalized',...
                'Position',[.1 .70 .8 .25]);
b2 = uicontrol(p,'Style','pushbutton','String','Edit image using Gestures','Callback',@buttonFunction,...
                'Units','normalized',...
                'Position',[.1 .40 .8 .25]);   
b3 = uicontrol(p,'Style','pushbutton','String','Perform operations(ml part)','Callback',@buttonFunction,...
                'Units','normalized',...
                'Position',[.1 .10 .8 .25]);